In [1]:
from aidds_buy.sys.utils.data_io import read_data, save_data

In [11]:
ppdf = read_data('data.pp.best', dtype={'acc_no': str})

In [12]:
ppdf.shape

(6159, 100)

In [14]:
ppdf[
    (260 < ppdf.line_length) & (ppdf.line_length < 290) & (ppdf.pole_cnt==3)
    # (0 < ppdf.line_length) & (ppdf.line_length < 360)
][['acc_no', 'cons_cost', 'pole_cnt', 'line_length']]

            acc_no  cons_cost  pole_cnt  line_length
937   476920204229   11126893       3.0        280.0
2351  477620213597    8876522       3.0        286.0
4835  475420223775    9055126       3.0        270.0
4901  475420224894   21446484       3.0        267.0

In [4]:
ppdf[ppdf.cons_cost > 9999999].head()

,acc_no,cons_cost,cont_cap,sup_type,office_id,pole_cnt,line_cnt,sl_cnt,pole_shape_G,pole_shape_O,...,sl_spec_16.0,sl_spec_22.0,sl_spec_25.0,sl_spec_35.0,sl_spec_38.0,sl_spec_60.0,sl_spec_70.0,sl_spec_100.0,sl_spec_120.0,sl_spec_240.0
0,477420193243,11598900,5,1,0,6.0,6.0,1.0,0.0,6.0,...,0,0,0,0,0,0,0,0,0,0
4,477420203306,16941740,5,1,0,4.0,3.0,1.0,0.0,4.0,...,0,0,1,0,0,0,0,0,0,0
11,477420203664,19943503,5,1,0,1.0,0.0,1.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
12,477420203712,13686684,5,1,0,7.0,6.0,1.0,2.0,5.0,...,0,0,0,0,0,0,0,0,0,0
13,477420203753,16154833,3,1,0,8.0,8.0,1.0,0.0,8.0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
ppdf.line_cnt.value_counts()

line_cnt
1.0     7244
2.0     3115
3.0     1486
4.0      781
0.0      460
5.0      397
6.0      218
7.0      101
8.0       41
9.0       24
10.0       9
11.0       7
Name: count, dtype: int64

In [7]:
save_data(ppdf[ppdf.pole_cnt==0], 'data.pp.zero')